### ISSUE TITLE
Preview window no longer showing

### ISSUE THREAD

**Issue by chrismalek** [FrodgE/textile-preview#2]
I have been using this for a while and it has been extremely helpful.  

Recently, the command no longer works. I am on OSX and I have everything up to the most recent version. When I try both commands nothing happens. I don't see any in the output windows. 

I am wondering if a vscode change broke this or if maybe there is some collision with another plugin which I know you can't answer.

**Comment by FrodgE** [comment]
Hi @chrismalek,
I'm glad to hear that you have found this extension helpful :smile:  I originally created it for myself and thought that perhaps others might like it also.

My apologies for taking so long to respond.  I saw your bug report but unfortunately did not have time to investigate it.  You are right that this problem was caused by a change within VS Code.  With the release of 1.33 the [vscode.previewHtml command was removed](https://code.visualstudio.com/updates/v1_33#_removing-the-vscodepreviewhtml-command).  I have now updated the extension to use the new ["webview" API](https://code.visualstudio.com/api/extension-guides/webview).

Version 1.0.2 should be available in the marketplace soon.
